[package]
name = "cpubench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpuid = "0.1.1"
csv = "1.2.1"
procfs = "0.15.1"
serde = { version = "1.0.156", features = ["derive"] }
